### PR TITLE
hfe: Compensate for opcodes during seeking

### PR DESCRIPTION
**Pull request by ejona86**
This reduces the worst-case observed skew from 3 ms to 50 us. There is a risk that in the future an opcode is added that is numerous and not evenly distributed, but that seems unlikely and we'd need to swap to a more complicated/advanced scheme.

### CODE REVIEW

**Comment by keirf** [comment]
I'm struggling with this one. The arithmetic is non obvious and so is the intent. I believe the code before this patch should at least get `im->cur_bc` approximately right? Or perhaps not because we base that on ticks_per_cell, and that value I'm not sure is even trustworthy and indeed doesn't account for opcodes...

Would we be better to seek the track bc and ticks positions as proportional to `start_ticks / stk_per_rev` (roughly speaking)? Rather than involving ticks_per_cell at all. It might be more direct. This new arithmetic makes me want to cry ;)

**Comment by keirf** [comment]
I realise it's not totally trivial as it will need some fixed point arithmetic to get a fraction of the track with say 16+ bits of precision. That would get us within a bitcell or two of the correct position, should be good enough. Probably need to divide/shift stk_per_rev down so that there's a factor of 2^-16 or so in the divisor.

What do you think?

**Comment by keirf** [comment]
Or perhaps I mean as a fraction of tracklen_ticks rather than stk_per_rev. I'm not sure now which of those is our most canonical best estimate of track timing? Anyway, picking such a thing and basing everything off that as directly as possible would seem to make sense.

**Comment by ejona86** [comment]
I think we must use `im->tracklen_ticks` in some way, as that is the only thing updated with the real track length in `hfe_rdata_flux()` when we reset to the start of the track. Is that a separate (seemingly minor) bug, that `stk_per_rev` should be updated, but isn't?

Starting over, the basis for what we need is:

```c
im->cur_bc = (start_ticks * 16) / im->ticks_per_cell
    * im->tracklen_bc / (im->tracklen_ticks / im->ticks_per_cell);
```

But that overflows, barely. Dividing the numerator and denominator by 8 seems without cost, since opcodes are bytes anyway. But that overflows for HD tracks.

What we care about is time accuracy, and number of bitcells scales with time so we could go with:

```c
uint32_t div = sampleclk_us(32) * 16;
im->cur_bc = (start_ticks * 16) / im->ticks_per_cell
    * (im->tracklen_bc * im->ticks_per_cell / div) / (im->tracklen_ticks / div);
```

And that would support ED. And then reorganizing some to improve readability:

```c
im->cur_bc = (start_ticks * 16) / im->ticks_per_cell;
im->cur_ticks = im->cur_bc * im->ticks_per_cell;
if (im->hfe.is_v3 && im->tracklen_ticks) {
    /* $Existing doc block from PR$ */
    /* Scale tracklen to avoid overflow. 200 ms with 32 us resolution is 13 bits,
     * which is small enough that if cur_bc is for an ED track the multiply won't
     * overflow. */
    uint32_t resolution = sampleclk_us(32) * 16;
    uint32_t assumed_tracklen = im->tracklen_bc * im->ticks_per_cell / resolution;
    uint32_t actual_tracklen = im->tracklen_ticks / resolution;
    im->cur_bc = im->cur_bc * assumed_tracklen / actual_tracklen;
}
if (im->cur_bc >= im->tracklen_bc) {
    im->cur_bc = 0;
    im->cur_ticks = 0;
}
```

Is that enough of an improvement?

**Comment by ejona86** [comment]
This has more accuracy, and is the same approach as the PR already had, but computes it a bit more straight-forward.

```c
if (im->hfe.is_v3 && im->tracklen_ticks) {
    /* $Existing doc block from PR$ */
    uint32_t assumed_tracklen = im->tracklen_bc;
    uint32_t actual_tracklen = im->tracklen_ticks / im->ticks_per_cell;
    im->cur_bc += im->cur_bc * (assumed_tracklen - actual_tracklen) / actual_tracklen;
}
```

The subtraction is pared with the `+=`, which is subtle. It would overflow ED when there's ~2.7% opcode overhead, and if we divide by 8 it'd overflow at 21% opcode overhead.

**Comment by ejona86** [comment]
> Is that a separate (seemingly minor) bug, that stk_per_rev should be updated, but isn't?

Oh, actually #823 fixes that.

**Comment by keirf** [comment]
My thinking on `stk_per_rev` vs `tracklen_ticks` is that the former is updated during seek while the latter is only updated on track reset in `hfe_rdata_flux()`. Your PR #823 also makes a decent stab at updating `stk_per_rev` during seek *and* updates it along with tracklen_ticks in `hfe_rdata_flux()`. Hence why it seems a better variable to consider canonical.

I'd be amenable to using `tracklen_ticks` if we update it alongside `stk_per_rev` during seek. In this way, both `tracklen_ticks` and `stk_per_rev` would be kept exactly in sync (during seek, and during track reset). Which seems to make sense to me: They'd both be a best estimate of track time length, just with different timebases.

As for the arithmetic I'll take another look! I will say that ED doesn't matter as the track length can't be represented in an HFE header! So we do only need to worry up to HD rate, or so.

**Comment by keirf** [comment]
Thinking to myself some more we could get rid of stk_per_rev as a variable and define it based on tracklen_ticks. A bit more work for some other time but it is nice to get rid of redundant variables.

**Comment by keirf** [comment]
I think I'm happy with your final suggested code. However I think `tracklen_ticks` should be always initialised earlier, either in this PR or as an extension to #823 so that you don't need to handle `tracklen_ticks` being 0 here. As previously mentioned in #823 too.

I think #822 and #823 are close now, and #825 needs some more wrestling as discussed.

**Comment by ejona86** [comment]
I've made the change (although this should change again once #823 is merged), but I've not yet fully tested it. My control test is busted and I need to investigate more.

**Comment by keirf** [comment]
Now #823 is merged can you squash and rebase? Also can you move the initialisation of `im->cur_ticks` later, to just before `im->ticks_since_flux = 0`? Then you should be able to avoid explicitly setting `im->cur_ticks = 0` as it will be handled by the normal initialisation.

**Comment by ejona86** [comment]
> Also can you move the initialisation of im->cur_ticks later, to just before im->ticks_since_flux = 0?

I don't think so, because the ticks shouldn't be impacted by the bc bytecode adjustment. In my original commit, I had `opcode_adj_bc` which was applied after cur_ticks was calculated, and the comment "Must be careful to exclude opcode_adj_bc from tick calculations." I got rid of that, but now cur_ticks has to be cleared if cur_bc is too large.

**Comment by keirf** [comment]
Yes of course. Okay let me see if I can wrap my hear around the arithmetic this time.

**Comment by keirf** [comment]
Ok, I thought about it and do agree with your code. Though I still find `cur_bc = ticks * tracklen_bc / tracklen_ticks` very tempting, as the obvious direct calculation albeit with a slow 64-bit division. How slow can it be? Let's say ten microseconds maybe: does that matter? The benefit is simple code, and which will never overflow.

Another question: Outside of `hfe_rdata_flux` do you think we would do better to use our "best guess average" `ticks_per_cell = write_bc_ticks * 16`? We don't know how `ticks_per_cell` will be adjusted by opcodes in the track, and perhaps it would be unfortunate to do arithmetic based on a temporarily high or low value in a variable-rate track. And at the moment these variations get propagated between tracks as we never reset `ticks_per_cell` to a default value in `setup_track` or `seek_track`.

On the other hand, perhaps `ticks_per_cell = write_bc_ticks * 16` is a rather rough estimate anyway, and we are better off with a value taken from an opcode?

This question feels less important if we did the direct calculation in `hfe_setup_track` which doesn't directly depend on `ticks_per_cell` at all.

**Comment by keirf** [comment]
Take a look at branch `hfe-seek` which implements what I'm talking about. The division is slow but manageable on a track setup path:
* STM32F105 @ 72MHz: 4.8us
* AT32F415 @ 144MHz: 2.4us
* AT32F435 @ 288MHz: 1.6us

The code is so very much simpler.

I still haven't decided what to do about `ticks_per_cell`. I'm tempted to always initialise it in `hfe_seek_track()`.

**Comment by keirf** [comment]
Unrelated to this PR, I have also your "Stream write to flash" patches on `img-writechunks` and `dsk-writechunks`, plus a tweak patch on top of each. Please can you have a look at those and, also, I have marked `XXX` a line in each which constrains `nr` by `CHUNK_SIZE - (off & 511)`. I think this line is unnecessary? Perhaps it has relevance in the 4.x async IO work. I wanted to check with you before deleting it though!

**Comment by ejona86** [comment]
> Take a look at branch hfe-seek which implements what I'm talking about

That code looks good.

> Outside of hfe_rdata_flux do you think we would do better to use our "best guess average" ticks_per_cell = write_bc_ticks * 16?

With the straight 64 bit division and your other small tweaks, I see you've avoided this issue for this calculation. Things will still be wrong if the bitrate is changing, but there's also not point in incremental improvements. For a read, the breakage will be small, with just the index being out-of-place. For writes, the breakage is big, with the write at the wrong location. But we'd need a very different approach to make writes accurate enough to be useful. (We really need the bitrate changes in a table with their bitcell positions.)

> I still haven't decided what to do about ticks_per_cell. I'm tempted to always initialise it in hfe_seek_track().

You could make a guess based on the track length. But beyond that, the only accurate value is found by encountering bytecodes. An old value is better than an average value, as at least it might be correct 50% of the time instead of wrong 100% of the time.

> I have marked XXX a line in each which constrains nr by CHUNK_SIZE - (off & 511). I think this line is unnecessary?

Well, at the very least we need to constrain it to CHUNK_SIZE, otherwise 1) we would overflow `wrbuf` and corrupt the cache, 2) we won't actually write it in sizes of CHUNK_SIZE and instead fully-buffer the sector in write_bc.

For the `off&511` part, I haven't been able to prove to myself that the I/O is aligned. Since various-sized sectors are allowed, if there are an odd number of 128 byte sectors in any track before the current sector, then the current write will not be aligned in the file. The `off&511` hurts nothing if things are aligned, but is an I/O optimization if they are misaligned. That was a correctness issue in v4, but is only an optimization in v3.

**Comment by ejona86** [comment]
>> I still haven't decided what to do about ticks_per_cell. I'm tempted to always initialise it in hfe_seek_track().
>
> You could make a guess based on the track length.

Oh, I see now you were recommending resetting to the file's default. That would be fine for reads, but for writes it would break a track that has different bitrate than the others. That's related to my "Assume bitrate does not change for the entire track, and write_bc_ticks already adjusted when reading" code comment in "hfe: Process opcodes when writing."

**Comment by keirf** [comment]
> Oh, I see now you were recommending resetting to the file's default. That would be fine for reads, but for writes it would break a track that has different bitrate than the others. That's related to my "Assume bitrate does not change for the entire track, and write_bc_ticks already adjusted when reading" code comment in "hfe: Process opcodes when writing."

I need to think about that. Most systems can only write at one bit rate, and I'd expect it to be close to the image-header-reported bit rate. But there are certainly exceptions. It's an issue for #825 anyway rather than here.

I am by the way suggesting adjusting `ticks_per_cell` / `write_bc_ticks` in `hfe_seek_track` rather than `hfe_setup_track`. 

I suppose part of the issue is that the bitrate opcode has a number of uses:
1. Bresenham-style micro adjustments to get the bitrate just so overall
2. Variable-rate intra-tracks (copy protections like Amiga's Copylock)
3. Variable-rate inter-tracks (C64 speedzones, Mac, Victor?, others maybe...)

Ho hum. Not one we're solving in this PR anyway.

**Comment by keirf** [comment]
> > I have marked XXX a line in each which constrains nr by CHUNK_SIZE - (off & 511). I think this line is unnecessary?
> 
> Well, at the very least we need to constrain it to CHUNK_SIZE, otherwise 1) we would overflow `wrbuf` and corrupt the cache, 2) we won't actually write it in sizes of CHUNK_SIZE and instead fully-buffer the sector in write_bc.
> 
> For the `off&511` part, I haven't been able to prove to myself that the I/O is aligned. Since various-sized sectors are allowed, if there are an odd number of 128 byte sectors in any track before the current sector, then the current write will not be aligned in the file. The `off&511` hurts nothing if things are aligned, but is an I/O optimization if they are misaligned. That was a correctness issue in v4, but is only an optimization in v3.

Ah yes good point about needing to constrain on `CHUNK_SIZE`, and of course we do that in the existing code; you've just added the `off&511` part. So let's see, if we had an 8kB unaligned sector. With your change we would write 1xunaligned_short, 6xaligned_full , 1xaligned_short. Without we would write everything unaligned and suffer extra copying in FatFS.

I guess I will add a comment and leave the code as you intended. :)

With that, I think these are good to go into `master`. Yay!

**Pull request closed without merging**
